name: Build Desktop Apps

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfuse2

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish (Windows & Linux)
        if: matrix.os != 'macos-latest'
        run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish (macOS Universal)
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --universal --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
